INSERT INTO answers (question_id, answer, correct_answer)
VALUES
(1, 'War', FALSE),
(1, 'Famine', FALSE),
(1, 'Pestilence', FALSE),
(1, 'Plague', TRUE),
(2, 'War', FALSE),
(2, 'Famine', FALSE),
(2, 'Pestilence', FALSE),
(2, 'Plague', TRUE),
(3, 'War', FALSE),
(3, 'Famine', FALSE),
(3, 'Pestilence', FALSE),
(3, 'Plague', TRUE),
(4, 'War', FALSE),
(4, 'Famine', FALSE),
(4, 'Pestilence', FALSE),
(4, 'Plague', TRUE),
(5, 'War', FALSE),
(5, 'Famine', FALSE),
(5, 'Pestilence', FALSE),
(5, 'Plague', TRUE),
(6, 'War', FALSE),
(6, 'Famine', FALSE),
(6, 'Pestilence', FALSE),
(6, 'Plague', TRUE),
(7, 'War', FALSE),
(7, 'Famine', FALSE),
(7, 'Pestilence', FALSE),
(7, 'Plague', TRUE),
(8, 'War', FALSE),
(8, 'Famine', FALSE),
(8, 'Pestilence', FALSE),
(8, 'Plague', TRUE),
(9, 'War', FALSE),
(9, 'Famine', FALSE),
(9, 'Pestilence', FALSE),
(9, 'Plague', TRUE),
(10, 'War', FALSE),
(10, 'Famine', FALSE),
(10, 'Pestilence', FALSE),
(10, 'Plague', TRUE),
(11, 'Tokyo', TRUE),
(11, 'Beijing', FALSE),
(11, 'Bangkok', FALSE),
(11, 'Ottawa', FALSE),
(12, 'London', FALSE),
(12, 'Washington DC', FALSE),
(12, 'Beijing', FALSE),
(12, 'Ottawa', TRUE),
(13, 'Paris', TRUE),
(13, 'Bruxelles', FALSE),
(13, 'Rome', FALSE),
(13, 'Lisbonnes', FALSE),
(14, 'Matthew Perry', TRUE),
(14, 'Lisa Kudrow', FALSE),
(14, 'Courtney Cox', FALSE),
(14, 'Matt LeBlanc', FALSE),
(15, 'Matthew Perry', FALSE),
(15, 'Lisa Kudrow', FALSE),
(15, 'Courtney Cox', FALSE),
(15, 'Matt LeBlanc', TRUE),
(16, 'Matthew Perry', FALSE),
(16, 'Lisa Kudrow', FALSE),
(16, 'Courtney Cox', TRUE),
(16, 'Matt LeBlanc', FALSE),
(17, 'Matthew Perry', FALSE),
(17, 'Lisa Kudrow', TRUE),
(17, 'Courtney Cox', FALSE),
(17, 'Matt LeBlanc', FALSE);
