DROP TABLE IF EXISTS user_attempts CASCADE;
CREATE TABLE user_attempts (
  id SERIAL PRIMARY KEY NOT NULL,

  attempt_id INTEGER NOT NULL REFERENCES attempts(id) ON DELETE CASCADE,
  answer_id INTEGER NOT NULL REFERENCES answers(id) ON DELETE CASCADE
);
