DROP TABLE IF EXISTS attempt_answers CASCADE;
CREATE TABLE attempt_answers (
  id SERIAL PRIMARY KEY NOT NULL,

  attempt_id INTEGER NOT NULL REFERENCES attempts(id) ON DELETE CASCADE,
  answer_id INTEGER NOT NULL REFERENCES answers(id) ON DELETE CASCADE
);
